Mise à jour des scripts d'installation sous mac d'après le travail sur linux

diff --git a/trunk/01_software/01_install/04_mac/conf-package/preupgrade b/trunk/01_software/01_install/04_mac/conf-package/preupgrade
--- a/trunk/01_software/01_install/04_mac/conf-package/preupgrade
+++ b/trunk/01_software/01_install/04_mac/conf-package/preupgrade
@@ -1,1 +1,20 @@
 #!/bin/bash
+
+if [ -f /Applications/XAMPP/xamppfiles/backup.sh ]; then
+    /Applications/XAMPP/xamppfiles/backup.sh
+    if [ $? -ne 0 ]; then
+        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting"
+        exit 1
+    fi
+    /etc/init.d/cultibox stop
+fi
+
+if [ -f /Applications/XAMPP/xamppfiles/get_version.sh ]; then
+    if [ -f /tmp/cultibox_version ]; then
+        rm /tmp/cultibox_version
+    fi
+    /Applications/XAMPP/xamppfiles/get_version.sh > /tmp/cultibox_version
+fi
+
+exit 0
+
