Correctif recette mac et linux 32

diff --git a/01_software/01_install/03_linux/conf-package/DEBIAN/postinst b/01_software/01_install/03_linux/conf-package/DEBIAN/postinst
--- a/01_software/01_install/03_linux/conf-package/DEBIAN/postinst
+++ b/01_software/01_install/03_linux/conf-package/DEBIAN/postinst
@@ -27,22 +27,22 @@ fi
 
 chown -R mysql /opt/cultibox/var/mysql
 
-/opt/cultibox/lampp restart
-sleep 2
-
-# Check if mysql is alive
-/opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-    sleep 4
-    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 -u root -h 127.0.0.1 ping >/dev/null 2>&1
-    if [ $? -ne 0 ]; then
-        echo "==== Error, the mysql service doesn't seem to be started... exiting ===="
-        exit 1
-    fi
-fi
-echo "... OK"
-
 if [ ! -f /tmp/cultibox_upgrade ]; then
+    /opt/cultibox/lampp restart
+    sleep 2
+
+    # Check if mysql is alive
+    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        sleep 4
+        /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 -u root -h 127.0.0.1 ping >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "==== Error, the mysql service doesn't seem to be started... exiting ===="
+            exit 1
+        fi
+    fi
+    echo "... OK"
+
     echo "  * Installing the Cultibox software..."
     /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
 
@@ -81,17 +81,36 @@ if [ ! -f /tmp/cultibox_upgrade ]; then
     echo "... OK"
 else 
     echo "  * A previous version of Cultibox was installed, upgrading your software..."
-    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
-    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/user_cultibox.sql
-
-    /opt/cultibox/run/load.sh
-    if [ $? -ne 0 ]; then
-        rm /tmp/cultibox_upgrade
-        if [ -f /tmp/cultibox_version ]; then
-            rm /tmp/cultibox_version
-        fi
+    if [ -d /tmp/cultibox_backup ]; then
+        cp -R /tmp/cultibox_backup/* /opt/cultibox/var/mysql/
+        rm -f /opt/cultibox/var/mysql/mysql/innodb_index_stats*
+        rm -f /opt/cultibox/var/mysql/mysql/innodb_table_stats*
+        rm -f /opt/cultibox/var/mysql/mysql/slave_master_info*
+        rm -f /opt/cultibox/var/mysql/mysql/slave_relay_log_info*
+        rm -f /opt/cultibox/var/mysql/mysql/slave_worker_info*
+    else
+        echo "==== Error, can't access to the cultibox backup directory... exiting ===="
         exit 1
     fi
+
+    /opt/cultibox/lampp restart
+    sleep 2
+
+    # Check if mysql is alive
+    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        sleep 4
+        /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 -u root -h 127.0.0.1 ping >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "==== Error, the mysql service doesn't seem to be started... exiting ===="
+            exit 1
+        fi
+    fi
+    echo "... OK"
+
+    /opt/cultibox/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
+    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/user_cultibox.sql
+    /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -h 127.0.0.1 --port=3891 mysql < /opt/cultibox/sql_install/five-tables.sql
 
     if [ -f /opt/cultibox/sql_install/update_joomla.sql ]; then
         /opt/cultibox/bin/mysql --defaults-extra-file=/opt/cultibox/etc/my-extra.cnf -f -h 127.0.0.1 --port=3891 < /opt/cultibox/sql_install/update_joomla.sql 
diff --git a/01_software/01_install/04_mac/conf-package/preinstall b/01_software/01_install/04_mac/conf-package/preinstall
--- a/01_software/01_install/04_mac/conf-package/preinstall
+++ b/01_software/01_install/04_mac/conf-package/preinstall
@@ -8,13 +8,13 @@ else
         rm -f /tmp/cultibox_upgrade
     fi
  
-         cat > /Applications/cultibox/xamppfiles/etc/my-extra.cnf << "EOF" 
+    cat > /Applications/cultibox/xamppfiles/etc/my-extra.cnf << "EOF" 
 [client]
 user="root"
 password="cultibox"
 EOF
 
-        cat > /Applications/cultibox/run/get_version.sh << "EOF"
+    cat > /Applications/cultibox/run/get_version.sh << "EOF"
 #!/bin/bash
 
 set -e
@@ -38,19 +38,37 @@ else
 fi
 exit 0
 EOF
-   if [ -d /Applications/cultibox ]; then
+
+    chmod +x /Applications/cultibox/run/get_version.sh
+
+    if [ -d /Applications/cultibox ]; then
       /Applications/cultibox/xamppfiles/xampp stop
       sleep 4
 
       # Remaining process:
       if [ "`ps aux|grep httpd|grep cultibox`" != "" ] || [ "`ps aux|grep mysql|grep cultibox`" != "" ]; then
         for process in `ps aux|grep httpd| grep cultibox| awk -F" " '{print $2}'`; do
-            sudo kill -9 $process
+            kill -9 $process
         done
 
         for process in `ps aux|grep mysql| grep cultibox| awk -F" " '{print $2}'`; do
-            sudo kill -9 $process
+            kill -9 $process
         done
+      fi
+
+      /Applications/cultibox/xamppfiles/xampp start
+      sleep 4 
+
+      if [ -f /Applications/cultibox/run/get_version.sh ]; then
+          if [ -f /tmp/cultibox_version ]; then
+              rm /tmp/cultibox_version
+          fi
+
+          /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
+          if [ $? -ne 0 ]; then
+              echo "==== Error during preinstall script, please check that the Cultibox software is correctly running, exiting ===="
+              exit 1
+          fi
       fi
 
       if [ -d /tmp/cultibox_backup ]; then
@@ -63,5 +81,8 @@ EOF
       cp -R /Applications/cultibox/xamppfiles/var/mysql/ib_logfile* /tmp/cultibox_backup/
  
       touch /tmp/cultibox_upgrade
+
+      /Applications/cultibox/xamppfiles/xampp stop
+      sleep 4
     fi
 fi
