Correction du load des tables sous linux, faut forcer le load en detruisant les tables...mais y a bon

diff --git a/01_software/01_install/03_linux/conf-package/DEBIAN/preinst b/01_software/01_install/03_linux/conf-package/DEBIAN/preinst
--- a/01_software/01_install/03_linux/conf-package/DEBIAN/preinst
+++ b/01_software/01_install/03_linux/conf-package/DEBIAN/preinst
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -x
+
 if [ -f /opt/cultibox/etc/php.ini ] && [ ! -f  /opt/cultibox/lampp ]; then
     echo "An old version of the Cultibox seems to be remaining in your system, please execute the following command before installing a new Cultibox version:"
     echo "      dpkg --purge cultibox"
@@ -75,7 +77,7 @@ mv $home/.cultibox/backup_joomla.bak.new $home/.cultibox/backup_joomla.bak
 chown $user_culti:$group_culti $home/.cultibox/*
 exit 0
 EOF
-
+        chmod +x /opt/cultibox/run/backup.sh
 
         cat > /opt/cultibox/run/get_version.sh << "EOF" 
 #!/bin/bash
@@ -101,18 +103,37 @@ else
 fi
 exit 0
 EOF
+        chmod +x /opt/cultibox/run/get_version.sh
 
-    #Killing remaining process
-    /opt/cultibox/lampp stop
-    if [ "`ps aux|grep cultibox`" != "" ]; then
-        for process in `ps aux|grep httpd|grep cultibox|awk -F" " '{print $2}'`; do
-            kill -9 $process 2>/dev/null
-        done
-    fi
-    /opt/cultibox/lampp start
-    sleep 2
+        #Killing remaining process
+        /opt/cultibox/lampp stop
+        if [ "`ps aux|grep httpd|grep cultibox`" != "" ]; then
+            for process in `ps aux|grep httpd|grep cultibox|awk -F" " '{print $2}'`; do
+                kill -9 $process 2>/dev/null
+            done
+        fi
+
+        /opt/cultibox/lampp start
+        sleep 2
+        /opt/cultibox/run/backup.sh
+        if [ $? -ne 0 ]; then
+            echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting ===="
+            exit 1
+        fi
+
+        if [ -f /opt/cultibox/run/get_version.sh ]; then
+            if [ -f /tmp/cultibox_version ]; then
+                rm /tmp/cultibox_version
+            fi
+            /etc/init.d/cultibox start
+            /opt/cultibox/run/get_version.sh > /tmp/cultibox_version
+            if [ $? -ne 0 ]; then
+                echo "==== Error during preinstall script, please check that the Cultibox software is correctly running, exiting ===="
+                exit 1
+            fi
+        fi
+
+        touch /tmp/cultibox_upgrade
     fi
 fi
 exit 0
-
-
