script de backup plus robuste

diff --git a/01_software/01_install/03_linux/conf-package/DEBIAN/prerm b/01_software/01_install/03_linux/conf-package/DEBIAN/prerm
--- a/01_software/01_install/03_linux/conf-package/DEBIAN/prerm
+++ b/01_software/01_install/03_linux/conf-package/DEBIAN/prerm
@@ -2,6 +2,10 @@
 
 if [ -d /opt/cultibox ]; then   
     /opt/lampp/backup.sh
+    if [ $? -ne 0 ]; then
+        echo "==== Error during the backup of your installation, please check that the Cultibox software is correctly running, exiting"
+        exit 1
+    fi
     /etc/init.d/cultibox stop
 fi
 
