test

diff --git a/04_CultiPi/01_Software/02_cultiConf/etc/cron.daily/cultipi b/04_CultiPi/01_Software/02_cultiConf/etc/cron.daily/cultipi
--- a/04_CultiPi/01_Software/02_cultiConf/etc/cron.daily/cultipi
+++ b/04_CultiPi/01_Software/02_cultiConf/etc/cron.daily/cultipi
@@ -1,5 +1,19 @@
 #!/bin/bash
 
+function check_package_manager {
+    count = 0
+    while [ "`ps ax|grep apt|grep -v 'grep'`" != "" ] || [ "`ps ax|grep dpkg|grep -v 'grep'`" != "" ];do
+        sleep 3
+        count = `expr $count + 1`
+
+        if [ $count -gt 20 ]; then
+            return 1
+        fi
+    done
+    return 0
+}
+
+
 while [ $# -gt 0 ]
 do
     case "$1" in
@@ -21,6 +35,12 @@ if [ "$now" != "yes" ]; then
     sleep $[ ( $RANDOM % 3600 )  + 1 ]s
 fi
 
+check_package_manager
+if [ $? -eq 1 ]; then
+    echo "--> Error, a package manager is already running... exiting"
+    exit 1
+fi
+
 
 #If there was an error whith dpkg/apt:
 /usr/bin/dpkg --configure -a --force-confdef --force-confold
@@ -38,7 +58,7 @@ elif [ "`dpkg -s cultipi 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes cultipi
     echo "...ok"
 else
-	echo "--> No upgrade available for Cultipi package"
+	echo "--> Cultipi package is up-to-date"
 fi
 
 if [ "`apt-get -u upgrade --assume-no|grep cultibox`" != "" ]; then
@@ -52,7 +72,7 @@ elif [ "`dpkg -s cultibox 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes cultibox
     echo "...ok"
 else
-	echo "--> No upgrade available for Cultibox package"
+	echo "--> Cultibox package is up-to-date"
 fi
 
 if [ "`apt-get -u upgrade --assume-no|grep cultiraz`" != "" ]; then
@@ -64,7 +84,7 @@ elif [ "`dpkg -s cultiraz 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes cultiraz
     echo "...ok"
 else
-	echo "--> No upgrade available for CultiRAZ package"
+	echo "--> CultiRAZ package is up-to-date"
 fi
 
 
@@ -77,7 +97,7 @@ elif [ "`dpkg -s cultitime 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes cultitime
     echo "...ok"
 else
-	echo "--> No upgrade available for Cultitime package"
+	echo "--> Cultitime package is up-to-date"
 fi
 
 if [ "`apt-get -u upgrade --assume-no|grep cultidoc`" != "" ]; then
@@ -89,7 +109,7 @@ elif [ "`dpkg -s cultidoc 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes cultidoc
     echo "...ok"
 else
-	echo "--> No upgrade available for Cultidoc package"
+	echo "--> Cultidoc package is up-to-date"
 fi
 
 if [ "`apt-get -u upgrade --assume-no|grep culticam`" != "" ]; then
@@ -101,7 +121,7 @@ elif [ "`dpkg -s culticam 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes culticam
     echo "...ok"
 else
-	echo "--> No upgrade available for Culticam package"
+	echo "--> Culticam package is up-to-date"
 fi
 
 if [ "`apt-get -u upgrade --assume-no|grep culticonf`" != "" ]; then
@@ -113,7 +133,7 @@ elif [ "`dpkg -s culticonf 2>/dev/null|grep Version`" == "" ]; then
     apt-get install -y  --force-yes culticonf
     echo "...ok"
 else
-	echo "--> No upgrade available for Culticonf package"
+	echo "--> Culticonf package is up-to-date"
 fi
 
 
