Correction de l'installation pour mac os x + correction du script load.sh de mac os x

diff --git a/01_software/01_install/04_mac/conf-package/postinstall b/01_software/01_install/04_mac/conf-package/postinstall
--- a/01_software/01_install/04_mac/conf-package/postinstall
+++ b/01_software/01_install/04_mac/conf-package/postinstall
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 echo "   * Configuring your CultiBox environment..."
 if [ ! -L /Applications/XAMPP ]; then
     ln -s /Applications/cultibox /Applications/XAMPP
@@ -28,10 +27,16 @@ sed -i '' "s/apache_user=daemon/apache_user=$user_culti/" /Applications/cultibox
 sed -i '' "s/apache_group=daemon/apache_group=$group_culti/" /Applications/cultibox/xamppfiles/properties.ini
 sed -i '' "s/mysql_port=3306/mysql_port=3891/" /Applications/cultibox/xamppfiles/properties.ini
 
-chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
-chown -R mysql /Applications/cultibox/xamppfiles/temp/mysql
-
 if [ ! -f /tmp/cultibox_upgrade ]; then
+    if [ -f /Applications/cultibox/xamppfiles/var/mysql/mysql.tar.gz ]; then
+        tar zxvfp /Applications/cultibox/xamppfiles/var/mysql/mysql.tar.gz -C /Applications/cultibox/xamppfiles/var/mysql/
+    else
+        echo "==== Missing mysql.tar.gz file... exiting ===="
+        exit 1 
+    fi
+
+    chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
+    chown -R mysql /Applications/cultibox/xamppfiles/temp/mysql
     /Applications/cultibox/xamppfiles/xampp start
     sleep 6
 
@@ -74,36 +79,44 @@ if [ ! -f /tmp/cultibox_upgrade ]; then
     echo "...OK"
 else
     echo "   * Upgrading the Cultibox software configuration..."
-    if [ -d /tmp/cultibox_backup ]; then
-        cp -R /tmp/cultibox_backup/* /Applications/cultibox/xamppfiles/var/mysql/
+    if [ -f /tmp/cultibox_version ]; then
+        #Get previous cultibox version
+        ver=`cat /tmp/cultibox_version`
+        #Removing architecture information
+        ver=`echo ${ver%%-*}`
+        ver=`echo ${ver//./}`
 
-        if [ -f /tmp/cultibox_version ]; then
-            #Get previous cultibox version
-            ver=`cat /tmp/cultibox_version`
-            #Removing architecture information
-            ver=`echo ${ver%%-*}`
-            ver=`echo ${ver//./}`
-
-            #upgrade from 1.1.XX to 1.2.XX: TO BE DELETED
-            if [ $ver -lt 1200 ]; then
-                rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_index_stats*
-                rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_table_stats*
-                rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_master_info*
-                rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_relay_log_info*
-                rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_worker_info*
+        #upgrade from 1.1.XX to 1.2.XX: TO BE DELETED
+        if [ $ver -lt 1200 ]; then
+            if [ -d /tmp/cultibox_backup ]; then
+                tar zxvfp /Applications/cultibox/xamppfiles/var/mysql/mysql.tar.gz -C /Applications/cultibox/xamppfiles/var/mysql/
+                cp -R /tmp/cultibox_backup/ib_logfile* /Applications/cultibox/xamppfiles/var/mysql/
+                cp -R /tmp/cultibox_backup/ibdata1* /Applications/cultibox/xamppfiles/var/mysql/
+                cp -R /tmp/cultibox_backup/mysql/* /Applications/cultibox/xamppfiles/var/mysql/mysql/
+            else
+                echo "==== Error, can't access to the cultibox backup directory... exiting ===="
+                exit 1
             fi
+        else
+           cp -R /tmp/cultibox_backup/* /Applications/cultibox/xamppfiles/var/mysql/ 
         fi
-    else
-        echo "==== Error, can't access to the cultibox backup directory... exiting ===="
-        exit 1
+        chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
+        chown -R mysql /Applications/cultibox/xamppfiles/temp/mysql
     fi
 
     /Applications/cultibox/xamppfiles/xampp start
     sleep 6
 
+    if [ $ver -lt 1200 ]; then
+        sleep 3
+        rm -Rf /Applications/cultibox/xamppfiles/var/mysql/mysql/*.ibd
+        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 --force mysql < /Applications/cultibox/sql_install/five-tables.sql
+        sleep 3
+    fi
+
     # Check if mysql is alive
     cpt=0
-    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -pcultibox -h 127.0.0.1 ping >/dev/null 2>&1
     while [ $? -ne 0 ]; do
         if [ $cpt -ge 5 ];then
             echo "==== Error, the mysql service doesn't seem be started... exiting ===="
@@ -111,23 +124,11 @@ else
         fi
         cpt=`expr $cpt + 1`
         sleep 6
-        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -pcultibox -h 127.0.0.1 ping >/dev/null 2>&1
     done
 
 
     echo "   * Configuring your Cultibox software..."
-    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
-    if [ $? -ne 0 ]; then
-        exit 1
-    fi
-
-    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/user_cultibox.sql
-    sleep 2
-    if [ $ver -lt 1200 ]; then
-        /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 mysql < /Applications/cultibox/sql_install/five-tables.sql
-    fi
-
-
     if [ -f /Applications/cultibox/sql_install/update_joomla.sql ]; then
         /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/update_joomla.sql
     fi
@@ -191,6 +192,11 @@ else
 
     rm -f /Applications/cultibox/xamppfiles/htdocs/cultibox/main/templates_c/*.ser 2>/dev/null
     echo "...OK"
+fi
+
+
+if [ -f /Applications/cultibox/xamppfiles/var/mysql/mysql.tar.gz ]; then
+    rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql.tar.gz
 fi
 
 echo "   * Installing CultiBox as a service..."
