Mise à jour recette Mac avec nouveau joomla + nouvelle recette sans sauvegarde/chargement des infos

diff --git a/01_software/01_install/04_mac/conf-package/postinstall b/01_software/01_install/04_mac/conf-package/postinstall
--- a/01_software/01_install/04_mac/conf-package/postinstall
+++ b/01_software/01_install/04_mac/conf-package/postinstall
@@ -31,23 +31,21 @@ sed -i '' "s/mysql_port=3306/mysql_port=3891/" /Applications/cultibox/xamppfiles
 chown -R mysql /Applications/cultibox/xamppfiles/var/mysql
 chown -R mysql /Applications/cultibox/xamppfiles/temp/mysql
 
-/Applications/cultibox/xamppfiles/xampp start
-sleep 6
+if [ ! -f /tmp/cultibox_upgrade ]; then
+    /Applications/cultibox/xamppfiles/xampp start
+    sleep 6
 
-# Check if mysql is alive
-/Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-    sleep 4
+    # Check if mysql is alive
     /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
     if [ $? -ne 0 ]; then
-        echo "==== Error, the mysql service doesn't seem be started... exiting ===="
-        exit 1
+        sleep 4
+        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "==== Error, the mysql service doesn't seem be started... exiting ===="
+            exit 1
+        fi
     fi
-fi
 
-echo "... OK"
-
-if [ ! -f /tmp/cultibox_upgrade ]; then
     echo "   * Configuring your Cultibox software..."
     /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
     if [ $? -ne 0 ]; then
@@ -74,18 +72,42 @@ if [ ! -f /tmp/cultibox_upgrade ]; then
     echo "...OK"
 else
     echo "   * Upgrading the Cultibox software configuration..."
-    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
-    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/user_cultibox.sql
-
-    /Applications/cultibox/run/load.sh
-    if [ $? -ne 0 ]; then
-        rm /tmp/cultibox_upgrade
-        if [ -f /tmp/cultibox_version ]; then
-            rm /tmp/cultibox_version
-        fi
+    if [ -d /tmp/cultibox_backup ]; then
+        cp -R /tmp/cultibox_backup/* /Applications/cultibox/xamppfiles/var/mysql/
+        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_index_stats*
+        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/innodb_table_stats*
+        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_master_info*
+        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_relay_log_info*
+        rm -f /Applications/cultibox/xamppfiles/var/mysql/mysql/slave_worker_info*
+    else
+        echo "==== Error, can't access to the cultibox backup directory... exiting ===="
         exit 1
     fi
+
+    /Applications/cultibox/xamppfiles/xampp start
     sleep 6
+
+    # Check if mysql is alive
+    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        sleep 4
+        /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 ping >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            echo "==== Error, the mysql service doesn't seem be started... exiting ===="
+            exit 1
+        fi
+    fi
+
+    echo "   * Configuring your Cultibox software..."
+    /Applications/cultibox/xamppfiles/bin/mysqladmin -u root -h 127.0.0.1 password cultibox
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
+
+    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/user_cultibox.sql
+    /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 mysql < /Applications/cultibox/sql_install/five-tables.sql
+
+
 
     if [ -f /Applications/cultibox/sql_install/update_joomla.sql ]; then
         /Applications/cultibox/xamppfiles/bin/mysql --defaults-extra-file=/Applications/cultibox/xamppfiles/etc/my-extra.cnf -h 127.0.0.1 --port=3891 < /Applications/cultibox/sql_install/update_joomla.sql
@@ -142,6 +164,7 @@ else
     fi
 
     rm /tmp/cultibox_upgrade
+    rm -Rf /tmp/cultibox_backup
     
     if [ -f /tmp/cultibox_version ]; then
         rm /tmp/cultibox_version
