Robustesse des tests de connection mysql sous mac os x

diff --git a/01_software/01_install/04_mac/conf-package/preinstall b/01_software/01_install/04_mac/conf-package/preinstall
--- a/01_software/01_install/04_mac/conf-package/preinstall
+++ b/01_software/01_install/04_mac/conf-package/preinstall
@@ -40,7 +40,7 @@ exit 0
 EOF
       chmod +x /Applications/cultibox/run/get_version.sh
       /Applications/cultibox/xamppfiles/xampp stop
-      sleep 4
+      sleep 6
 
       # Remaining process:
       if [ "`ps aux|grep httpd|grep cultibox`" != "" ] || [ "`ps aux|grep mysql|grep cultibox`" != "" ]; then
@@ -54,18 +54,24 @@ EOF
       fi
 
       /Applications/cultibox/xamppfiles/xampp start
-      sleep 4 
-
+      sleep 6
       if [ -f /Applications/cultibox/run/get_version.sh ]; then
           if [ -f /tmp/cultibox_version ]; then
               rm /tmp/cultibox_version
           fi
 
+          cpt=0
           /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
-          if [ $? -ne 0 ]; then
-              echo "==== Error during preinstall script, please check that the Cultibox software is correctly running, exiting ===="
-              exit 1
-          fi
+          while [ $? -ne 0 ]; do
+              if [ $cpt -ge 5 ];then
+                  echo "==== Error during preinstall script, please check that the Cultibox software is correctly running, exiting ===="
+		  exit 1
+              fi
+              $cpt=`expr $cpt + 1`
+	      sleep 6
+              /Applications/cultibox/run/get_version.sh > /tmp/cultibox_version
+
+          done 
       fi
 
       if [ -d /tmp/cultibox_backup ]; then
@@ -80,7 +86,7 @@ EOF
       touch /tmp/cultibox_upgrade
 
       /Applications/cultibox/xamppfiles/xampp stop
-      sleep 4
+      sleep 6
     else 
         # Remaining process:
         if [ "`ps aux|grep httpd|grep cultibox`" != "" ] || [ "`ps aux|grep mysql|grep cultibox`" != "" ]; then
